
version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
      - 8000:8000
    volumes:
      - ./:/var/www/html
networks:
  default:
    external: true
    name: docker_banco_mysql_default